service: sls-tracker-sync-nextbite

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: ${opt:aws-profile, "bowtie_agency"}
  environment:
    SLS_STAGE: ${self:custom.stage}

custom:
  stage: ${opt:stage, self:provider.stage}
  version: v1
  baseUrl: "api/${self:custom.version}"
  # serverless-offline:
    # httpPort: 4000
    # prefix: dev

functions:
  sync:
    handler: handler.sync
    events:
      - http:
          path: ${self:custom.baseUrl}/sync
          method: post
          # cors: true
