service: sls-tracker-sync

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: ${opt:aws-profile, "bowtie_agency"}
  environment:
    SLS_STAGE: ${self:custom.stage}
    # https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/#authentication
    JIRA_API_USER: charlie@bowtie.co
    JIRA_API_TOKEN: xxx
    JIRA_API_URL: https://heliosinteract.atlassian.net

custom:
  stage: ${opt:stage, self:provider.stage}
  version: v1
  baseUrl: "api/${self:custom.version}"
  # serverless-offline:
    # httpPort: 4000
    # prefix: dev

functions:
  sync:
    handler: handler.sync
    events:
      - http:
          path: ${self:custom.baseUrl}/sync
          method: post
          # cors: true
